---
title: "Figure3a"
author: "Giang Nguyen"
date: "4/30/2021"
output: html_document
---

```{r}
library("readxl")
```

```{r}
read_excel("C:\\Users\\giang nguyen\\Desktop\\Makeup_data_figure_3.xlsx")
```

```{r}
my_data <- read_excel("C:\\Users\\giang nguyen\\Desktop\\Makeup_data_figure_3.xlsx")
```

```{r}
library(tidyverse)
```

```{r}
plot1 <- ggplot(my_data, aes( x= reorder(Gene, OR, FUN= median), y = OR)) + geom_boxplot(fill= "white", alpha = 0.5) + stat_boxplot(geom = 'errorbar', width = 0.2) + geom_point(alpha=0.2)

```


```{r}
plot2 <- ggplot(my_data, aes(x= reorder(Gene, OR, FUN= median), y= OR, size = No.sample, color = Resistance_level )) + geom_point(alpha=0.3) +   scale_radius(range = c(0.01, 5))
```


```{r}
plot3 <-  ggplot(my_data, aes(x= reorder(Gene, OR, FUN= median), y= OR)) + geom_point(aes(color = Resistance_level, size = No.sample), alpha=0.7) +   scale_size(range = c(0.01, 6)) + ylab("log odds ratio") + xlab ("gene") + geom_boxplot(fill= "white", alpha = 0.5) + stat_boxplot(geom = 'errorbar', width = 0.2) +  geom_point(alpha=0.3)
```

```{r}
read_excel("C:\\Users\\giang nguyen\\Desktop\\Makeup_data_figure_3.xlsx")
```
```
```{r}
my_data <- read_excel("C:\\Users\\giangnguyen\\Desktop\\Makeup_data_figure_3.xlsx")
```

```{r}
plot10 <- my_data %>%
    arrange(MIC_OR) %>%
    mutate(name = factor(Resistance_level, levels=c("Unknown", "Low", "Intermediate", "High"))) %>%
    ggplot( aes(x=name, y=MIC_OR, fill= name)) +
    geom_boxplot() + 
    xlab("Resistance level") + ylab("log odds ratio")+  theme(legend.position = "none")+ stat_boxplot(geom = 'errorbar', width = 0.2) + geom_point(alpha=0.2)
```

```{r}

```

